title: Blog Bibliotheks- und Archivinformatik
author: Nathalie
email: nathalie.wicki@stud.fhgr.ch
description: > # this means to ignore newlines
Lerntagebuch des Moduls Bibliotheks- und Archivinformatik FS2024

# social links

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
