title: Blog Bibliotheks- und Archivinformatik
author: Nathalie
email: nathalie.wicki@stud.fhgr.ch
description: > # this means to ignore newlines
  Lerntagebuch im Modul Bibliotheks- und Archivinformatik FS2024
show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
